version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package sonar:sonar -Dsonar.host.url=ec2-3-230-26-162.compute-1.amazonaws.com -Dsonar.login=93c807805de1d6078eaff02a7b0259a77a85a508 -Dsonar.login=admin -Dsonar.password=admin
artifacts:
  files:
    - target/messageUtil-1.0.jar
